### ISSUE TITLE
bug: WalletConnectConnector not supporting single chain

### ISSUE THREAD

**Issue by Hi-Nemo** [wagmi-dev/references#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

 "@wagmi/core": "^1.2.0"

### Current Behavior

Hello Team,

I have upgraded my app to **"@wagmi/core": "^1.2.0"**, and using **WalletConnectConnector**. The multichain feature is working fine but whenever I am using single chain and scanning the QR code, I am getting the below issue on console.

```
browser.js:202 Error: Chains must not be empty
    at index.es.js:1:3373
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:26262:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:25948:55
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:25948:36)
    at _ZoneDelegate.invokeTask (zone.js:401:60)
```

**Here is my code sample:**
   
```
   const ms = new MetaMaskConnector({....});
    const wc= new WalletConnectConnector({
      chains: [goerli],
      options: {
        projectId: '***---***'
      },
    })
```

```
const myApp = createConfig({
  autoConnect: true,
  connectors: [ms, wc],
  publicClient,
  webSocketPublicClient,
});
```

**Connect function:**
```
  async function connectNow(type: string): void {
    await connect({
      connector: type === 'metamask' ? ms :  wc
    })
  }
```

**Comment by 0xAsimetriq** [comment]
Unable to re-create when using mainnet, so I assume wallet does not support goerli and errors when there is nothing else to approve. We are working on an option of allowing no chains at all, where you will be able to connect and send `wallet_addEthereumChain` in your case.

**Comment by glitch-txs** [comment]
@olegshilov we already merged a PR with the fix :) you can check in the issue you shared btw

**Comment by olegshilov** [comment]
> @olegshilov we already merged a PR with the fix :) you can check in the issue you shared btw

Hi. As I write before I use latest released connectors package, but no result. You can see it on repo I created for. https://github.com/olegshilov/wagmi-walletconnect-error/blob/main/package.json#L25

**Comment by glitch-txs** [comment]
I think it hasn't been released yet

**Comment by jxom** [comment]
releasing now

**Comment by olegshilov** [comment]
The error persists despite my efforts to resolve it.

I have made the necessary updates to my MRP in order to provide you with accurate information.

As previously mentioned twice, I have utilized the "WalletConnectConnector" directly from the package, specifically the version that you have already released. In order to ensure accuracy, I have upgraded the "@wagmi/connectors" package to version "2.6.4," which was released subsequent to the merge of the referenced pull request. However, these actions did not yield the desired outcome.

Furthermore, I have now updated to the latest version of "wagmi" (version 1.3.6), yet the error persists.

I am open to the possibility that I might have made an error in my implementation. If this is indeed the case, I kindly request your guidance in identifying and rectifying the issue.

**Comment by glitch-txs** [comment]
my bad! Didn't noticed optionalChains are also passed on the connect function, they need to be filtered there as well

**Comment by olegshilov** [comment]
So maybe reopen this issue? And thx for fast response.

**Comment by glitch-txs** [comment]
I reopened the PR, could you please review it? @jxom Thanks :D

**Comment by olegshilov** [comment]
@jxom @glitch-txs thx guys. all work fine now.

**Comment by francesco-gaglione** [comment]
Same issue and if I try to update these versions:

`
    "typescript": "^5.1.6",
    "viem": "1.2.6",
    "wagmi": "1.3.6",
    "@wagmi/chains": "1.4.0",
    "@wagmi/connectors": "2.6.4"
`

an error occurred:
rror: No wagmi config found. Ensure you have set up a config: https://wagmi.sh/react/config

**Comment by francesco-gaglione** [comment]
Same error with:
`
  "wagmi": "1.3.7",
    "@wagmi/chains": "1.4.0",
    "@wagmi/connectors": "2.6.4"
`

**Comment by 0xAsimetriq** [comment]
@francesco-gaglione 

> Also, you shouldn't be installing
> 
> ```
> "@wagmi/chains": "1.4.0", "@wagmi/connectors": "2.6.4"
> ```
> 
> And instead import ones that are packaged with `wagmi`, otherwise there can be edge cases

**Comment by olegshilov** [comment]
> Same error with: `"wagmi": "1.3.7", "@wagmi/chains": "1.4.0", "@wagmi/connectors": "2.6.4"`

Can you check working version here?
https://codesandbox.io/p/github/olegshilov/wagmi-walletconnect-error

**Comment by francesco-gaglione** [comment]
@olegshilov same error with only wagmi as dependencies at version 1.3.7, other notes I'm using next js with pages folder, so should be all static generated and the error happen in prerendering build. 

The link u give used 1.3.7

**Comment by olegshilov** [comment]
@francesco-gaglione can you provide some code on codesandbox or github?

**Comment by francesco-gaglione** [comment]
unfortunately I can't share the repo because it's private, but I'm preparing a new repo with the reproduction of the issue and I'll link it here.

**Comment by glitch-txs** [comment]
If the component rerenders the variables are redeclated and you're passing a new config each time. If you need to set up the chains from a component you can do this when calling connect function I think

**Comment by 0xAsimetriq** [comment]
@francesco-gaglione this is now venturing way beyond wagmi/walletconnect support, so I suggest you reference

1. https://docs.walletconnect.com/2.0/web/web3modal/react/wagmi/installation
2. https://wagmi.sh/react/getting-started

If you are still unable to start, try picking one of the examples at https://github.com/WalletConnect/web3modal-examples and building from there

**Comment by Hi-Nemo** [comment]
KIndly reopen this post and don't close it until you people release the new package.

**Comment by olegshilov** [comment]
@Hi-Nemo 
> KIndly reopen this post and don't close it until you people release the new package.

They release it https://github.com/wagmi-dev/wagmi/releases/tag/wagmi%401.3.7
